services:
  predict:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./repo/:/usr/src/predict/repo
    networks:
      - predict-public
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

networks:
  predict-public:
    driver: bridge

volumes:
  db: